from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image

from docuxray.graph import build_document_graph
from docuxray.io import ocr_words_from_dicts
from docuxray.tables import attach_tables, load_tables
from docuxray.types import DocumentPage


def generate_document_graph(
    image_path: str | Path,
    ocr_json_path: str | Path,
    output_path: str | Path,
    *,
    tables_path: str | Path | None = None,
) -> Path:
    image_path = Path(image_path)
    ocr_json_path = Path(ocr_json_path)
    output_path = Path(output_path)

    ocr_data = json.loads(ocr_json_path.read_text(encoding="utf-8"))
    words_data = ocr_data.get("words", ocr_data) if isinstance(ocr_data, dict) else ocr_data
    if not isinstance(words_data, list):
        raise ValueError("OCR JSON must be a list or an object with a 'words' list")

    words = ocr_words_from_dicts(words_data)
    with Image.open(image_path) as image:
        page = DocumentPage(page=0, width=image.width, height=image.height, image_path=str(image_path))

    graph = build_document_graph([page], words)
    tables, rows, cells = load_tables(tables_path)
    attach_tables(graph, tables, rows, cells)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(graph.to_dict(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Build DocuXray document graph JSON from image + OCR JSON.")
    parser.add_argument("--image", required=True, help="Input document image")
    parser.add_argument("--ocr-json", required=True, help="DocuXray OCR JSON generated by generate_ocr_json.py")
    parser.add_argument("--output", required=True, help="Output document graph JSON path")
    parser.add_argument("--tables", help="Optional table structure JSON/CSV")
    args = parser.parse_args()

    output_path = generate_document_graph(
        args.image,
        args.ocr_json,
        args.output,
        tables_path=args.tables,
    )
    print(f"Document graph written to: {output_path}")


if __name__ == "__main__":
    main()
